services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    command: /app/.venv/bin/python -m pydentity
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks: [pydentity]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pydentity
      POSTGRES_PASSWORD: pydentity
      POSTGRES_DB: pydentity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pydentity"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks: [pydentity]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks: [pydentity]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks: [pydentity]

volumes:
  pgdata:
  redis_data:

networks:
  pydentity:
    external: true
