"""initial

Revision ID: 189ae4c62f01
Revises:
Create Date: 2026-03-07 19:13:33.412503

"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "189ae4c62f01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("domain_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("permissions", sa.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("domain_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("email_verification_is_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verification_token_hash", sa.LargeBinary(), nullable=True),
        sa.Column(
            "email_verification_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("credentials_password_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "credentials_password_reset_token_hash", sa.LargeBinary(), nullable=True
        ),
        sa.Column(
            "credentials_password_reset_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "credentials_password_history", sa.ARRAY(sa.LargeBinary()), nullable=False
        ),
        sa.Column("login_tracking_failed_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "login_tracking_lockout_expiry", sa.DateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("domain_id", sa.String(), nullable=False),
        sa.Column("user_fk", sa.Integer(), nullable=False),
        sa.Column("user_domain_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_trusted", sa.Boolean(), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_fk"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain_id"),
        sa.UniqueConstraint("fingerprint", name="devices_fingerprint_key"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_fk", sa.Integer(), nullable=False),
        sa.Column("role_fk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_fk"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_fk"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_fk", "role_fk"),
        sa.UniqueConstraint("user_fk", "role_fk", name="uq_user_role"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("domain_id", sa.String(), nullable=False),
        sa.Column("user_fk", sa.Integer(), nullable=False),
        sa.Column("device_fk", sa.Integer(), nullable=False),
        sa.Column("user_domain_id", sa.String(), nullable=False),
        sa.Column("device_domain_id", sa.String(), nullable=False),
        sa.Column("refresh_token_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "refresh_token_family_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column("refresh_token_family_generation", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("session_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_refresh", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expiry", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_fk"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_fk"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.drop_table("user_roles")
    op.drop_table("devices")
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
