"""

Revision ID: b506ca0dbce6
Revises:
Create Date: 2026-03-17 08:14:30.410535

"""
from typing import TYPE_CHECKING

from alembic import op
import sqlalchemy as sa


if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'b506ca0dbce6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('target_entity_type', sa.String(length=50), nullable=True),
    sa.Column('target_entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_user_id', 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_category', 'audit_events', ['category'], unique=False)
    op.create_index('ix_audit_events_occurred_at', 'audit_events', ['occurred_at'], unique=False)
    op.create_index('ix_audit_events_target', 'audit_events', ['target_entity_type', 'target_entity_id'], unique=False, postgresql_where='target_entity_type IS NOT NULL')
    op.create_index('ix_audit_events_trace_id', 'audit_events', ['trace_id'], unique=False, postgresql_where='trace_id IS NOT NULL')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('email_verification_is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token_hash', sa.LargeBinary(), nullable=True),
    sa.Column('email_verification_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credentials_password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('credentials_password_reset_token_hash', sa.LargeBinary(), nullable=True),
    sa.Column('credentials_password_reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credentials_password_history', sa.ARRAY(sa.LargeBinary()), nullable=False),
    sa.Column('login_tracking_failed_attempts', sa.Integer(), nullable=False),
    sa.Column('login_tracking_lockout_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.Column('user_domain_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_fk', 'fingerprint', name='uq_devices_user_fingerprint')
    )
    op.create_index('ix_devices_domain_id', 'devices', ['domain_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.Column('role_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_fk'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_fk', 'role_fk'),
    sa.UniqueConstraint('user_fk', 'role_fk', name='uq_user_role')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=False),
    sa.Column('device_fk', sa.Integer(), nullable=False),
    sa.Column('user_domain_id', sa.String(), nullable=False),
    sa.Column('device_domain_id', sa.String(), nullable=False),
    sa.Column('refresh_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_family_id', sa.String(), nullable=False),
    sa.Column('refresh_token_family_generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('session_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_refresh', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_fk'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_index('ix_sessions_refresh_token_hash', 'sessions', ['refresh_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_refresh_token_hash', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('user_roles')
    op.drop_index('ix_devices_domain_id', table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('ix_audit_events_trace_id', table_name='audit_events', postgresql_where='trace_id IS NOT NULL')
    op.drop_index('ix_audit_events_target', table_name='audit_events', postgresql_where='target_entity_type IS NOT NULL')
    op.drop_index('ix_audit_events_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_category', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_user_id', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
