from pydentity.authentication.domain.account.aggregate import Account
from pydentity.authentication.domain.account.errors import (
    AccountAlreadyClosedError,
    AccountAlreadySuspendedError,
    AccountNotActiveError,
    AccountNotLockedError,
    AccountNotUnverifiedError,
    AccountUnverifiedError,
    CannotRemoveCredentialError,
    DuplicateTOTPSecretError,
    EmailAlreadyTakenError,
    MFAAlreadyEnabledError,
    MFANotEnabledError,
    MFARequiresCredentialError,
    PasswordPolicyViolationError,
    PasswordReuseError,
    TOTPSecretNotFoundError,
)
from pydentity.authentication.domain.account.events import (
    AccountClosed,
    AccountLocked,
    AccountRegistered,
    AccountSuspended,
    AccountUnlocked,
    EmailVerificationRequested,
    EmailVerified,
    MFADisabled,
    MFAEnabled,
    PasswordChanged,
    PasswordResetCompleted,
    RecoveryCodeConsumed,
    RecoveryCodesGenerated,
    TOTPSecretAdded,
    TOTPSecretRemoved,
)
from pydentity.authentication.domain.account.repository import AccountRepository
from pydentity.authentication.domain.account.services import (
    PreventDuplicateEmail,
    PreventPasswordReuse,
)
from pydentity.authentication.domain.account.value_objects import (
    AccountStatus,
    EmailAddress,
    EncryptedTOTPSecret,
    HashedPassword,
    HashedPasswordHistory,
    HashedRecoveryCode,
    HashedRecoveryCodeSet,
    LockoutPolicy,
    LockoutState,
    LockReason,
    MFAStatus,
    PasswordPolicy,
    UnlockReason,
)
from pydentity.shared_kernel import AccountId

__all__ = [
    # aggregate_id
    "AccountId",
    # value_objects
    "AccountStatus",
    "EmailAddress",
    "EncryptedTOTPSecret",
    "HashedPassword",
    "HashedPasswordHistory",
    "HashedRecoveryCode",
    "HashedRecoveryCodeSet",
    "LockReason",
    "LockoutPolicy",
    "LockoutState",
    "MFAStatus",
    "PasswordPolicy",
    "UnlockReason",
    # events
    "AccountClosed",
    "AccountLocked",
    "AccountRegistered",
    "AccountSuspended",
    "AccountUnlocked",
    "EmailVerificationRequested",
    "EmailVerified",
    "MFADisabled",
    "MFAEnabled",
    "PasswordChanged",
    "PasswordResetCompleted",
    "RecoveryCodeConsumed",
    "RecoveryCodesGenerated",
    "TOTPSecretAdded",
    "TOTPSecretRemoved",
    # errors
    "AccountAlreadyClosedError",
    "AccountAlreadySuspendedError",
    "AccountNotActiveError",
    "AccountNotLockedError",
    "AccountNotUnverifiedError",
    "AccountUnverifiedError",
    "CannotRemoveCredentialError",
    "EmailAlreadyTakenError",
    "DuplicateTOTPSecretError",
    "MFAAlreadyEnabledError",
    "MFANotEnabledError",
    "MFARequiresCredentialError",
    "PasswordPolicyViolationError",
    "PasswordReuseError",
    "TOTPSecretNotFoundError",
    # aggregate
    "Account",
    # domain services
    "PreventDuplicateEmail",
    "PreventPasswordReuse",
    # repository
    "AccountRepository",
]
